### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by danielriddell21** [ivkos/botyo#1]
Hey i have an issue on installation, i am very confused with how it all works? Would u be able to help me out

**Comment by bobland1** [comment]
Love the work btw. I am currently using AWS, with a linux AMI.

**Comment by ivkos** [comment]
Hey @bobland1 

I haven't used Linux AMI, but as far as I have read, it allows you to install packages, so you need to first install Docker and Docker Compose, then follow the instructions in the [README](https://github.com/ivkos/botyo/blob/master/README.md#running-inside-docker) to install Botyo. I really can't tell you if you'll need to spend any money on your instance, but my guess is you won't.

Hopefully, the following resources would help you set your environment up:
* [Installing Docker on Linux AMI](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html)
* [Installing Docker on Linux distributions](https://docs.docker.com/engine/installation/linux/)

I'm currently running an instance of Botyo on a Starter VC1S server provided by [Scaleway](https://www.scaleway.com/) for €2.99/month and it has proven capable enough. 2GB RAM is a little on the low side (esp. if you're dealing with huge chat histories) but adding some swap can mitigate that. For just €2.99 it's good enough, in my opinion.

Let me know if I can help with anything else.

**Comment by bobland1** [comment]
docker-compose: command not found
 I get this error now

**Comment by bobland1** [comment]
Okay dw fixed that issue

**Comment by bobland1** [comment]
![image](https://cloud.githubusercontent.com/assets/25375432/22387338/0b1419cc-e4d3-11e6-953b-1c2fd6c3ec67.png)

**Comment by bobland1** [comment]
Thats what i see atm :)

**Comment by bobland1** [comment]
If i am able to talk to you on skype or something about this it would be great
