### ISSUE TITLE
Handling 3rd party modules

### ISSUE THREAD

**Issue by tomaszwro** [ivkos/botyo#2]
Hi. First and foremost - thanks for a great tool, we're looking forward to use it.

Have you thought how to handle 3rd party modules? I've just started to develop one. 

The easiest way would probably be to submit a PR with a module disabled by default - but what if it has some crazy dependencies, that you wouldn't like to pull by default.

So for the long run it would be good to have a way to include other modules available either on npm or github. I can probably make a PR if you don't have resources at the moment, but let's first agree on how this should work.

I haven't yet looked too much at the code, but how about:
1. adding the npm module or github repo to dependencies in package.json
2. adding an entry in config.yaml with a flag that it's an external module so that it can find it (I'm assuming it won't be able to autodiscover)

**Comment by ivkos** [comment]
Hey @fmwr 
Thanks for your feedback. This is something I have been thinking about for a while. I'll try to design a new architecture soon. Most probably, I'll extract the core functionality into a smaller npm module, the preinstalled modules into separate ones, and implement expose some API methods, e.g. `botyo.registerCommand(ThirdPartyCommand)`, `botyo.registerFilter(ThirdPartyFilter)`.
