### ISSUE TITLE
Listen to self 

### ISSUE THREAD

**Issue by dimitrisA** [ivkos/botyo#3]
I am not sure this is the best place to write this (I'm new here) but the following config property could be added 
- self: true # listen to your own messages

To allow the bot to respond to messages send by the fb profile in which it runs. [ I am running it from my own profile so its useful for me ]

Code just takes  very little tweaking in FacebookClient.js file:
>Add this to constructor
`this.listentoself = this.config.get("self");`

>And this in login function
```
if(this.listentoself) {
                	api.setOptions({
                		logLevel: "warn",
                		selfListen: true
                	}); } else { // same code with selfListen: false}
```

Anyways, again congrats for this great project! The new additions were great! Thank you!

**Comment by ivkos** [comment]
Hey @dimitrisA 
I implemented your suggestion. It's configurable via the `app.selfListen` property in config.yaml and by default it's set to false.

Thanks for you suggestion and feedback. Glad you find Botyo useful.

**Comment by dimitrisA** [comment]
That's great
