### ISSUE TITLE
Spotify 401 Unauthorized

### ISSUE THREAD

**Issue by calvinbui** [ivkos/botyo#4]
When using the Spotify command, I receive the following error:

```
bot_1    | { [WebapiError: Unauthorized]
bot_1    |   name: 'WebapiError',
bot_1    |   message: 'Unauthorized',
bot_1    |   statusCode: 401,
bot_1    |   _friendlyHandled: true }
```

**Comment by ivkos** [comment]
Botyo has been thoroughly refactored for third-party module support. This bug is fixed in the Spotify module:

https://github.com/ivkos/botyo-command-spotify

Thanks for your report.
